# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    runs-on: ${{ matrix.runner.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Test Resource
      run: dotnet publish --use-current-runtime
    - name: Test (fail)
      run: dotnet run --project Runner -- load; echo $?
      continue-on-error: true
    - name: Test (pass)
      run: dotnet run --project Runner; echo $?
